public class OpportunityHandlerController {
                public static void onBeforeInsert(List<Opportunity> OpportunityList) {
                                /*
                                call before insert actions
                                */
                }

                public static void onBeforeUpdate(List<Opportunity> OpportunityList, Map<Id, Opportunity> mapOpptyOld) {
                                /*
                                call before update actions
                                */
                }

                public static void onAfterInsert(List<Opportunity> OpportunityList) {
                                /*
                                call after insert actions
                                */
                }

                public static void onAfterUpdate(List<Opportunity> OpportunityList, Map<Id, Opportunity> mapOpptyOld) {
                                /*
                                call after update actions
                                */
                }

                public static void onAfterDelete(List<Opportunity> OpportunityList, Map<Id, Opportunity> mapOpptyOld) {
                                /*
                                call after delete actions
                                */
                }

                public static void onBeforeDelete(List<Opportunity> OpportunityList, Map<Id, Opportunity> mapOpptyOld) {
                                /*
                                call before delete actions
                                */
                }

}